### ISSUE TITLE
Use of undefined constant _isCurl in RequestresponseManager.php

### ISSUE THREAD

**Issue by ankurhora** [InMobi/api-monetization#5]
line 60 
	public function fetchResponse($requestJson,$userAgent,$carrierIP) {
		if(_isCurl == false) {                                                                         // this
			echo "Curl is not supported.";
			return null;
		}

throws ans error of Use of undefined constant _isCurl in RequestResponseManager.php

**Comment by rish2cool** [comment]
Made check for function call instead of variable, issue should be resolved now.

**Comment by ankurhora** [comment]
The issue still exist... 
PHP Fatal error:  Call to undefined function _iscurl()

**Comment by rish2cool** [comment]
I've made the function scope public, please re-check.

**Comment by ankurhora** [comment]
still the same!

**Comment by rish2cool** [comment]
This should now get resolved, I had not scoped $this call.
